### ISSUE TITLE
FSST from lance

### ISSUE THREAD

**Issue by berkus** [spiraldb/fsst#37]
Are you folks aware of the impl from [lance](https://github.com/lancedb/lance/tree/main/rust/lance-encoding/compression-algo/fsst)?

Do you know how well you compare?

**Comment by lwwmanning** [comment]
@berkus yep! we came across it

The Lance impl is based on the same paper/algorithm, though theirs was somewhat coupled to Lance v2. Specifically, most of the code appears to be an exact 1:1 translation of the C++ code from the paper. Their [public API entrypoint](https://github.com/lancedb/lance/blob/v0.18.0/rust/lance-encoding/compression-algo/fsst/src/fsst.rs#L1232-L1234) writes the contents of a Lance v2 FSST-encoded file to a buffer (magic bytes, header, and all).

This crate is intended for reuse in other code bases, we wrap it up in Vortex [here](https://github.com/spiraldb/vortex/tree/develop/encodings/fsst).

We haven't tried a head-to-head benchmark against the Lance impl, though @a10y spent quite a bit of time optimizing this crate's throughput. We mainly compared against the paper & the original C++ impl. 

We currently get 1-3GB/s of encoding/decoding throughput on a Macbook Pro, which is comparable to the original paper's AVX-512 implementation (on Intel). We also have plans for a portable SIMD implementation that should speed things up even more.

**Comment by berkus** [comment]
@lwwmanning thank you so much for this info! Definitely enforces my bias towards using this crate :)
